# Generated by Django 4.0.4 on 2022-05-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_text_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='dictionnaire',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='norme',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='lang',
            field=models.CharField(choices=[('ar', 'ar'), ('fr', 'fr')], default='ar', max_length=50),
        ),
    ]
