# Generated by Django 4.0.4 on 2022-05-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_normalization_text_transcription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='dictionnaire',
            new_name='normalization',
        ),
        migrations.RemoveField(
            model_name='text',
            name='norme',
        ),
    ]
