# Generated by Django 4.0.4 on 2022-05-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_dictionnaire_text_normalization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='transcription',
        ),
    ]
