# Generated by Django 4.0.4 on 2022-05-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_text_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='transcription',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='lang',
            field=models.CharField(choices=[('arabe', 'arabe'), ('fr', 'fr')], default='ar', max_length=50),
        ),
    ]
