# Generated by Django 4.0.4 on 2022-05-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_text_transcription_alter_text_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='lang',
            field=models.CharField(choices=[('ar', 'ar'), ('fr', 'fr')], default='ar', max_length=50),
        ),
    ]
